title: Ontimize Web documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Ontimize Web Repository: https://github.com/OntimizeWeb
  Components: /components/

versions:
  - url: https://ontimizeweb.github.io/docs/v4/
    title: 4.x.x
    selected: false
  - url: https://ontimizeweb.github.io/docs/v8/
    title: 8.x.x
    selected: false
  - url: /
    title: 15.x.x
    selected: true

page_excerpts: true