# Develop override settings

url                     : https://ontimizeweb.github.io
baseurl                 : "/docs/v8"

analytics:
  provider              : false

comments:
  disqus:
    shortname           : "mmistakes-dev"

sass:
  style: expanded