# Develop override settings

url                     : https://ontimizeweb.github.io
#baseurl                 : "/docs"

analytics:
  provider              : false

comments:
  disqus:
    shortname           : "mmistakes-dev"

sass:
  style: expanded