# Develop override settings

url                     : http://localhost:4000
baseurl                 : "/docs"

analytics:
  provider              : false

comments:
  disqus:
    shortname           : "mmistakes-dev"

sass:
  style: expanded