logo: images/logo-ontimize-blanco.png

search_enabled: true

description: Welcome to the Ontimize v15 documentation!
theme: just-the-docs

versions:
  - url: https://ontimizeweb.github.io/docs/v4/
    title: 4.x.x
    selected: false
  - url: https://ontimizeweb.github.io/docs/v8/
    title: 8.x.x
    selected: false
  - url: /
    title: 15.x.x
    selected: true

page_excerpts: true

github:
  - name: Onitmize Web
    url: https://github.com/OntimizeWeb
    icon: images/github-240-light.png

color_scheme: ontimize-light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: grey-dk
  important:
    title: Important
    color: grey-dk
  note:
    title: Note
    color: blue
    opacity: 1
  warning:
    title: Warning
    color: red

exclude:
  - docs