
class : "ODialogConfig"

attributes: [{
  name: "alertType",
  type: "AlertType => 'info' | 'warn' | 'error'",
  default: "",
  required: "",
  description: "The type of preconfigured alert dialogs"
},{
  name: "okButtonText",
  type: "string",
  default: "",
  required: "",
  description: "The text of 'ok' button"
},{
  name: "cancelButtonText",
  type: "string",
  default: "",
  required: "",
  description: "The text of 'cancel' button"
},{
  name: "icon",
  type: "string",
  default: "",
  required: "",
  description: "The material icon of the dialog"
}]