class : "OServiceComponent"

propertiesColumns: ["Name", "Type", "Required", "Description"]

inheritedAttributes: [{
  component: "OServiceBaseComponent",
  path: "components/service/service-base",
  attributes: ["attr", "static-data", "service", "service-type", "query-method", "entity", "keys", "parent-keys", "columns", "query-on-init", "query-on-bind", "query-rows", "insert-method", "update-method", "paginated-query-method", "delete-method", "pageable", "store-state"]
}]

attributes: [{
  name: "title",
  type: "string",
  default: "",
  required: "",
  description: "Title in exported files"
},{
  name: "visible"
},{
  name: "enabled"
},{
  name: "detail-mode"
},{
  name: "detail-form-route"
},{
  name: "recursive-detail"
},{
  name: "edit-form-route"
},{
  name: "recursive-edit"
},{
  name: "detail-button-in-row"
},{
  name: "detail-button-in-row-icon"
},{
  name: "edit-button-in-row"
},{
  name: "edit-button-in-row-icon"
},{
  name: "insert-button"
},{
  name: "row-height"
},{
  name: "insert-form-route"
},{
  name: "recursive-insert"
}, {
  name: "controls"
}]
