directive: "table-config"
title: "Table configuration"

inheritedAttributes:
  [
    {
      component: "OTableComponent",
      path: "components/data/table/api",
      attributes:
        [
          "visible",
          "detailButtonInRow",
          "detailButtonInRowIcon",
          "editButtonInRow",
          "editButtonInRowIcon",
          "editFormRoute",
          "rowHeight",
          "autoAdjust",
          "autoAlignTitles",
          "collapseGroupedColumns",
          "columnsVisibilityButton",
          "defaultVisibleColumns",
          "deleteButton",
          "disableSelectionFunction",
          "detailMode",
          "editionMode",
          "enabled",
          "exportButton",
          "exportServiceType",
          "filterColumnActiveByDefault",
          "groupable",
          "groupedColumns",
          "horizontalScroll",
          "keepSelectedItems",
          "multipleSort",
          "nonHidableColumns",
          "pageSizeOptions",
          "orderable",
          "quickFilterFunction",
          "resizable",
          "rowClass",
          "selectAllCheckbox",
          "selectAllCheckboxVisible",
          "selectionMode",
          "showConfigurationOption",
          "showExpandableIconFunction",
          "showFilterOption",
          "showPaginatorFirstLastButtons",
          "showReportOnDemandOption",
          "showChartsOnDemandOption",
          "showResetWidthOption",
          "sortColumns",
          "virtualScroll",
          "visibleColumns",
          "visibleExportDialogButtons",
          "selectionOnRowClick",
        ],
    },
  ]
