name: Release Docs
on:
  pull_request:
    types: [closed]
    branches:
      - 15.x.x
  workflow_dispatch:
    inputs:
      BASELINE:
        description: 'Baseline branch of documentation'
        required: true
        default: '15.x.x'
      TARGET_FOLDER:
        description: 'Target version folder'
        required: true
        default: 'next'
        type: choice
        options:
          - 'v15'
          - 'next'


jobs:
  build-docs:
    name: Publish doc
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' ||
      (github.event.pull_request.merged == true && contains(join(github.event.pull_request.labels.*.name, ', '), 'release-docs'))
    steps:
      - name: Process input parameters
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET_PATH="${{ github.event.inputs.TARGET_FOLDER }}"
          else
            TARGET_PATH="v15"
          fi
          echo "TARGET_PATH=$TARGET_PATH" >> "$GITHUB_ENV"
          BASELINE_BRANCH=${{ github.event.inputs.BASELINE || github.ref }}
          echo "BASELINE_BRANCH=${BASELINE_BRANCH#refs/heads/}" >> "$GITHUB_ENV"
      
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASELINE_BRANCH }}
          fetch-depth: 0

      - name: Bundler Cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Jekyll
        uses: helaili/jekyll-action@master
        with:
          jekyll_env: deploy
          jekyll_build_options: --baseurl /docs/${{ env.TARGET_PATH }} --config _config.yml,_config.deploy.yml
          target_branch: gh-pages
          target_path: ${{ env.TARGET_PATH }}
          keep_history: true
          token: ${{ secrets.GITHUB_TOKEN }}
